#!/usr/bin/env python3
"""Extract .context.md files from engine/ and editor/ into MkDocs API reference pages.

Usage:
    python website/scripts/generate_api_docs.py
    python website/scripts/generate_api_docs.py --output-dir /tmp/api-docs

The script finds all .context.md files under engine/ (and editor/ at repo root),
wraps each one with MkDocs-compatible YAML front matter, and writes the result
to the output directory as <subsystem>.md.

Exit codes:
    0  All expected .context.md files found and processed.
    1  One or more .context.md files are missing or empty.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Map from source .context.md path (relative to repo root) to output filename
# and human-readable title.
SUBSYSTEM_MAP: dict[str, tuple[str, str]] = {
    "engine/core/.context.md":       ("core.md",       "Core"),
    "engine/renderer/.context.md":   ("renderer.md",   "Renderer"),
    "engine/audio/.context.md":      ("audio.md",      "Audio"),
    "engine/physics/.context.md":    ("physics.md",    "Physics"),
    "engine/scripting/.context.md":  ("scripting.md",  "Scripting"),
    "engine/networking/.context.md": ("networking.md", "Networking"),
    "engine/scene/.context.md":      ("scene.md",      "Scene"),
    "editor/.context.md":            ("editor.md",     "Editor"),
}

AUTO_GEN_NOTICE = (
    "!!! info \"Auto-generated\"\n"
    "    This page is auto-generated from the engine's `.context.md` files.\n"
    "    Do not edit this file by hand -- run the extraction script instead:\n"
    "    `python website/scripts/generate_api_docs.py`\n"
)


def find_repo_root() -> Path:
    """Walk up from this script's location to find the repo root (contains engine/)."""
    candidate = Path(__file__).resolve().parent
    for _ in range(10):
        if (candidate / "engine").is_dir():
            return candidate
        candidate = candidate.parent
    print("ERROR: Could not find repo root (no engine/ directory in ancestors).", file=sys.stderr)
    sys.exit(1)


def build_front_matter(title: str, description: str) -> str:
    """Return MkDocs YAML front matter block."""
    return (
        "---\n"
        f"title: \"{title} API Reference\"\n"
        f"description: \"{description}\"\n"
        "---\n\n"
    )


def process_context_file(
    repo_root: Path,
    rel_path: str,
    out_filename: str,
    title: str,
    output_dir: Path,
) -> bool:
    """Read a .context.md, wrap it, and write to output_dir. Returns True on success."""
    source = repo_root / rel_path

    if not source.exists():
        print(f"  MISSING: {rel_path}")
        return False

    content = source.read_text(encoding="utf-8")
    if not content.strip():
        print(f"  EMPTY:   {rel_path}")
        return False

    description = f"FastFreeEngine {title} subsystem API reference"
    front_matter = build_front_matter(title, description)

    output_path = output_dir / out_filename
    output_path.write_text(
        front_matter + AUTO_GEN_NOTICE + "\n" + content,
        encoding="utf-8",
    )

    try:
        display_path = output_path.relative_to(repo_root)
    except ValueError:
        display_path = output_path
    print(f"  OK:      {rel_path} -> {display_path}")
    return True


def main() -> int:
    repo_root = find_repo_root()

    parser = argparse.ArgumentParser(
        description="Generate MkDocs API pages from engine .context.md files.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=repo_root / "website" / "docs" / "api",
        help="Directory to write generated .md files (default: website/docs/api/)",
    )
    args = parser.parse_args()

    output_dir: Path = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Repo root:  {repo_root}")
    print(f"Output dir: {output_dir}")
    print()

    all_ok = True
    processed = 0

    for rel_path, (out_filename, title) in SUBSYSTEM_MAP.items():
        ok = process_context_file(repo_root, rel_path, out_filename, title, output_dir)
        if ok:
            processed += 1
        else:
            all_ok = False

    print()
    print(f"Processed {processed}/{len(SUBSYSTEM_MAP)} subsystems.")

    if not all_ok:
        print("WARNING: Some .context.md files were missing or empty.", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
